### PR TITLE
Fixed Database Insertion bug and Started migrating UI content into the DB

### LINKED ISSUE #62: 55-Loading-models-from-DB
This feature is intended to load all entity models from the database

### PR DESCRIPTION
**Pull request by alexolowo**
This pull request contains features such as loading projects from the database and updating edited content on the UI in the DB

### CODE REVIEW

**Review by ronald-tutor — DISMISSED** [review]
Impressive work! Your database implementation follows SOLID Principles excellently. The low coupling between methods and cohesive classes make calling necessary functions a breeze. The interaction between the UI, Database and individual use cases seem to follow both SOLID and CA as well. Plus, it sets us up for easy integration of a user login/signup feature in the Kanban board. Great job!

**Review by wennapengooin — DISMISSED** [review]

**Review by SoumyadipSarker — DISMISSED** [review]
Great work in refactoring the database controllers. This would remove many of the flaws of existing controllers and would help us better adhere to clean architecture

**Review by ronald-tutor — DISMISSED** [review]
In addition to the comments above, had to fix minor merge conflicts.

**Review by wennapengooin — DISMISSED** [review]

**Review by igor-kan — APPROVED** [review]

**Review by srisais — DISMISSED** [review]

**Review by igor-kan — DISMISSED** [review]
I resolved the conflicts with main. Merge when you are ready. What is the use of com.sun.glass.ui.Clipboard in your pr? Why did you switch to opencsv if we used apache csv up til now?

**Review by igor-kan — APPROVED** [review]

**Comment by igor-kan** [comment]
What is the use of com.sun.glass.ui.Clipboard in your pr? Why did you switch to opencsv if we used apache csv up til now?

**Review by SoumyadipSarker — APPROVED** [review]

**Review by wennapengooin — APPROVED** [review]

**Pull request merged**
