### PR TITLE
30 feature 18 drag and drop implementation

### PR DESCRIPTION
**Pull request by alexolowo**
This is a pull request to merge the drag and drop features of the board as well as some small UI changes

### CODE REVIEW

**Review by ronald-tutor — DISMISSED** [review]
The drag-and-drop functionality works really well on my end too. This is one of the app's main features so it being implemented is great! Thank you!

**Comment by igor-kan** [comment]
Why Project entity class makes use of outer layer object, i.e. Column entity model, and all List<Column> are changed to List<ColumnModel>? Isn't ColumnModel class for that purppose?

**Review by igor-kan — CHANGES_REQUESTED** [review]
Great implementation of drag and drop functionality! Why Project entity class makes use of outer layer object, i.e. Column entity model, and all Column lists in Project entity are changed to ColumnModel List? ProjectModel already implements ColumnModel list so I suggest making ProjectModel to pass data between layers.

**Review by wennapengooin — DISMISSED** [review]

**Review by srisais — DISMISSED** [review]

**Review by alexolowo — COMMENTED** [review]
noted, I will adjust accordingly. Thank you for catching that

**Review by igor-kan — APPROVED** [review]

**Review by ronald-tutor — APPROVED** [review]

**Review by wennapengooin — APPROVED** [review]

**Pull request merged**
