### PR TITLE
32 feature 19 database interface

### LINKED ISSUE #32: [Feature 19] Database interface & Change task name and description

### PR DESCRIPTION
**Pull request by SoumyadipSarker**
Created the Data Access Interface, which is to be used by the various use case classes and another interface to be used by the presenter. Also includes ProjectFactory, ColumnFactory and TaskFactory and a new database SearchController.

### CODE REVIEW

**Review by srisais — DISMISSED** [review]
This is an awesome addition to the project, Soumyadip!
It's a great idea to add the factories and better abstract our codebase by having the database store entity models, rather than the entities themselves. This will allow for easier refactorability down the line, if we ever do need to change something to, for example, the entity models.
Also, I really like the inline comments! They help make the code much easier to understand, especially when just skimming through a file :)

**Review by igor-kan — DISMISSED** [review]
Great and well documented addition! I was thinking about factories too because of encountering conflicts between use cases, entities and entity models - I also had problems but with ColumnModels list. Interfaces for the use cases and the presenter are good, too. and made a pull request. You used default methods in the data access interface but why the Searchcontroller and Search gateway were created? Is it a better way to abstract the project structure or because there are problems with existing search implementation? Also, it is great that you replaced entities with entity models in the database implementation which will help maintainability and flexibility. * Are you using Java 17?

**Review by ronald-tutor — APPROVED** [review]
These changes are essential for the feature to change details of the task. Your comments are really helpful too. Thank you!

**Review by srisais — APPROVED** [review]
Reapproving the new changes 👍👍👍

**Review by wennapengooin — APPROVED** [review]
Thanks for making the interfaces for the use cases and the presenter. I also updated the classes in the database to use models instead of using entities so hopefully when my branch merges, it merges slowly.

**Comment by wennapengooin** [comment]
Oh also, I don't think your code for ur feature of 'updating task details' updates the task entities themselves, or perhaps you haven't implemented that portion yet. For my Create Task feature, I was thinking to reserve the Use Case Class for strictly changing the attributes of the entities, and then having the interactor class deal with the gateway to change the info in the database. If u have another method for changing the entities please lmk!

**Pull request merged**
