### PR TITLE
Delete new task feature and add new task feature

### PR DESCRIPTION
**Pull request by wennapengooin**
similar to Soumayadip's update task details feature, implemented add task use case to update the database and create new task entities. HAS NOT IMPLEMENTED HOW TO ADD THE NEWLY CREATED TASK ENTITY TO THE RESPECTIVE COLUMN'S LIST OF TASKS.Implemented delete task use case to update the database. HAS NOT IMPLEMENTED HOW TO DELETE TASK ENTITY FROM COLUMN ENTITY'S LIST OF TASKS.

### CODE REVIEW

**Review by ronald-tutor — APPROVED** [review]
Thanks for fixing the issues. The usage of factories is helpful for the implementation. We only need to add/delete the task from the column entity which we can all work together to implement.

**Review by igor-kan — CHANGES_REQUESTED** [review]
Great implementation of task manipulation use cases and the connectivity.
Nice refactoring and changing use cases’ dependancy from entities to entity models 

One tiny syntax error: import statements repeat directories, e.g.
import a_enterprise_business_rules.entities.entities.Column; or package a_enterprise_business_rules.entities.entities;
Also resolution of conflicts with main branch is needed.

**Comment by wennapengooin** [comment]
commits made onn buggy version of main, rejected

**Comment by wennapengooin** [comment]
commits made onn buggy version of main, rejected

**Pull request closed without merging**
