### PR TITLE
1 feature 1 create entities

### LINKED ISSUE #1: [Feature 1] Create Entities
Create the 3 entity classes:

1. Task
2. Column
3. Project

They should be in that specific order, as, the Task entity is depended on by the Column entity, and the Column entity is depended on by the Project entity.

These 3 entity classes should work independently of any other classes. It's dependency graph (each class points at what it depends on) should look something like this:
Task <-- Column <-- Project

Ensure that when you write any code, you document the newly created code. Include enough information so that someone can come back to this (or even yourself) and understand how the method work / what the attribute does / etc. based on the documentation. We probably would rather have long documentation than have to stare at the code and figure out how it works, so, don't be afraid of writing a longer explanation if it makes it clearer for someone to understand.

### PR DESCRIPTION
**Pull request by srisais**
I created the 3 main entity classes, with their respective attributes and methods.

I have written the javadocs as well for all the attributes, methods, and for the classes. Since the methods are quite simple (no more than 5-10 lines each), I haven't written much (moreover, any) in-line documentation.

Just for clarity, I will add this later.

### CODE REVIEW

**Review by ronald-tutor — DISMISSED** [review]

**Comment by srisais** [comment]
We need 3 people to approve each pull request, before being able to merge to main, according to the Quercus instructions (we also made the GitHub repository settings as such)

**Comment by srisais** [comment]
Closing this PR, since I have new code in this branch. whoopsie lol.

**Comment by srisais** [comment]
Ope, never mind, I don't need to create a new PR for this. lol.

**Review by ronald-tutor — DISMISSED** [review]

**Comment by srisais** [comment]
It looks like Pull Requests will merge the latest commit to the branch, so, I didn't need to close and reopen this branch lol.

**Review by ronald-tutor — APPROVED** [review]

**Review by ronald-tutor — APPROVED** [review]

**Review by ronald-tutor — APPROVED** [review]

**Review by wennapengooin — APPROVED** [review]

**Review by alexolowo — APPROVED** [review]

**Comment by alexolowo** [comment]
Entities created appropriately and skeleton for GUI is well implemented

**Comment by srisais** [comment]
pogchamp

pull request merged 😎






lool

**Pull request merged**
